version: 2
updates:
- package-ecosystem: bun
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  groups:
    minor-and-patch:
      update-types:
      - minor
      - patch
