[build]
command = "bun run deploy"
publish = "app/dist"

[build.environment]
IS_DEPLOYMENT = "true"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/dof/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/workbox-*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/dof/workbox-*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/registerSW.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/dof/registerSW.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/dof/sw.js"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/dof/manifest.webmanifest"

[headers.values]
Cache-Control = "public, max-age=3600"
